// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package global

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Cta() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-red-700\"><div class=\"mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8\"><div class=\"sm:flex sm:items-center sm:justify-between\"><div class=\"text-center sm:text-left\"><h1 class=\"text-2xl font-bold text-gray-200 sm:text-3xl\">Looking for Suspension Service?</h1><p class=\"mt-1.5 text-sm text-gray-200\">Head over to our Contact page and request a quote or give us a\r call!</p></div><div class=\"mt-4 flex flex-col gap-4 sm:mt-0 sm:flex-row sm:items-center\"><a href=\"/contact\" class=\"btn btn-outline\">Contact Us </a> <a href=\"tel:+15202365474\" class=\"btn btn-outline\">Call Now</a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
