// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Hero() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"hero h-full md:h-screen\" style=\"background-image: url(/static/images/backgrounds/hero_bg.webp);\"><div class=\"hero-overlay bg-black bg-opacity-50\"></div><div class=\"hero-content min-h-96 text-neutral-content rounded-md\"><div class=\"max-w-screen-sm md:max-w-screen-lg md:text-left text-center\"><h1 class=\"mb-2 text-5xl md:text-7xl font-bold\">WELCOME</h1><h1 class=\"mb-5 m:mb-10 text-5xl md:text-7xl font-bold\">TO ZR<b class=\"text-red-700\">1</b> TAMPA</h1><p class=\"text-2xl md:text-3xl w-full md:w-3/5 mb-5\">The premier suspension service center for all things motocross and offroad.</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
