// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SplitContent() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section><div class=\"mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-16\"><div class=\"grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-16\"><div class=\"relative h-64 overflow-hidden rounded-lg sm:h-80 lg:order-last lg:h-full\"><img alt=\"ZR1 Forks Image\" src=\"/static/images/content/fork_complete.jpg\" class=\"absolute inset-0 h-full w-full object-cover\" id=\"scroller\"></div><div class=\"lg:py-24\"><h2 class=\"text-3xl font-bold sm:text-4xl\">Tampa's Suspension Service Center</h2><p class=\"mt-4 text-white-200\">We specialize in suspension services in the Tampa area, providing a range of solutions such as rebuilds, repairs, revalving, replacement, and upgrades. Whatever your suspension needs, we got you covered at ZR1.\r</p><a href=\"/contact\" class=\"mt-8 btn btn-outline\">Get A Quote Today\r</a></div></div></div></section><script>\r\n\t\tScrollReveal().reveal('#scroller', { delay: 200, reset: true });\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
