// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package about

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func AboutCody() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section><div class=\"mx-auto max-w-screen-xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8\"><div class=\"max-w-3xl\"><h2 class=\"text-3xl font-bold sm:text-4xl\">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod alias doloribus impedit.\r</h2></div><div class=\"mt-8 grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-16\"><div class=\"relative h-96 overflow-hidden sm:h-96 md:h-full\"><img alt=\"Cody\" src=\"/static/images/content/cody_owner.jpg\" class=\"absolute inset-0 h-full w-full object-cover\"></div><div class=\"lg:py-16\"><article class=\"space-y-4 text-gray-600\"><p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aut qui hic atque tenetur quis\r eius quos ea neque sunt, accusantium soluta minus veniam tempora deserunt? Molestiae\r eius quidem quam repellat.\r</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum explicabo quidem\r voluptatum voluptas illo accusantium ipsam quis, vel mollitia? Vel provident culpa\r dignissimos possimus, perferendis consectetur odit accusantium dolorem amet voluptates\r aliquid, ducimus tempore incidunt quas. Veritatis molestias tempora distinctio\r voluptates sint! Itaque quasi corrupti, sequi quo odit illum impedit!\r</p></article></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
